import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>CASAS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}>
        <div className={styles.left}>
          <Link href="/">
            <div className={styles.logo}>
              <Image
                src="/img/logo.png"
                alt="casas"
                className={styles.logoImg}
                width={1773}
                height={1772}
                priority
              />
            </div>
          </Link>
        </div>
        <div className={styles.center}>portafolio</div>
        <div className={styles.right}>contacto</div>
      </nav>
      <main className={styles.main}>
        <section className={styles.header}>
          <div className={styles.video}>
            <video autoPlay muted loop>
              <source src="img/video-test-1.mp4" type="video/mp4" />
            </video>
          </div>
          <div className={styles.content}>
            <div className={styles.title}>Paramount +</div>
            <div className={styles.subtitle}> A mountain of entertaiment</div>
          </div>
        </section>
        <section className={styles.videos}>
          <div className={styles.left}>
            <div className={styles.videoType1}>
              <video autoPlay muted loop>
                <source src="img/video-test-2.mp4" type="video/mp4" />
              </video>
              <div className={styles.content}>
                <div className={styles.title}>Paramount +</div>
                <div className={styles.subtitle}>
                  A mountain of entertaiment
                </div>
              </div>
            </div>
            <div className={styles.videoType2}>
              <video autoPlay muted loop>
                <source src="img/video-test-3.mp4" type="video/mp4" />
              </video>
              <div className={styles.content}>
                <div className={styles.title}>Paramount +</div>
                <div className={styles.subtitle}>
                  A mountain of entertaiment
                </div>
              </div>
            </div>
            <div className={styles.videoType3}>
              <video autoPlay muted loop>
                <source src="img/video-test-4.mp4" type="video/mp4" />
              </video>
              <div className={styles.content}>
                <div className={styles.title}>Paramount +</div>
                <div className={styles.subtitle}>
                  A mountain of entertaiment
                </div>
              </div>
            </div>
            <div className={styles.videoType4}>
              <video autoPlay muted loop>
                <source src="img/video-test-1.mp4" type="video/mp4" />
              </video>
              <div className={styles.content}>
                <div className={styles.title}>Paramount +</div>
                <div className={styles.subtitle}>
                  A mountain of entertaiment
                </div>
              </div>
            </div>
          </div>
          <div className={styles.right}>
            <div className={styles.videoType2}>
              <video autoPlay muted loop>
                <source src="img/video-test-3.mp4" type="video/mp4" />
              </video>
              <div className={styles.content}>
                <div className={styles.title}>Paramount +</div>
                <div className={styles.subtitle}>
                  A mountain of entertaiment
                </div>
              </div>
            </div>

            <div className={styles.videoType4}>
              <video autoPlay muted loop>
                <source src="img/video-test-1.mp4" type="video/mp4" />
              </video>
              <div className={styles.content}>
                <div className={styles.title}>Paramount +</div>
                <div className={styles.subtitle}>
                  A mountain of entertaiment
                </div>
              </div>
            </div>
            <div className={styles.videoType1}>
              <video autoPlay muted loop>
                <source src="img/video-test-2.mp4" type="video/mp4" />
              </video>
              <div className={styles.content}>
                <div className={styles.title}>Paramount +</div>
                <div className={styles.subtitle}>
                  A mountain of entertaiment
                </div>
              </div>
            </div>
            <div className={styles.videoType3}>
              <video autoPlay muted loop>
                <source src="img/video-test-4.mp4" type="video/mp4" />
              </video>
              <div className={styles.content}>
                <div className={styles.title}>Paramount +</div>
                <div className={styles.subtitle}>
                  A mountain of entertaiment
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className={styles.footer}>
        CASAS 2023® todos los derechos reservados
      </footer>
    </>
  );
}
