import Head from "next/head";
import Link from "next/link";
import styles from "@/styles/Home.module.css";
import { Nav } from "@/components/Nav/Nav";
import { Footer } from "@/components/Footer/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>CASAS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className={styles.main}>
        <section className={styles.header}>
          <div className={styles.video}>
            <video autoPlay muted loop>
              <source src="img/video-test-1.mp4" type="video/mp4" />
            </video>
          </div>
          <Link href="/proyecto">
            <div className={styles.content}>
              <div className={styles.title}>Paramount +</div>
              <div className={styles.subtitle}> A mountain of entertaiment</div>
            </div>
          </Link>
        </section>
        <section className={styles.videos}>
          <div className={styles.left}>
            <div className={styles.videoType1}>
              <Link href="/proyecto">
                <video autoPlay muted loop>
                  <source src="img/video-test-2.mp4" type="video/mp4" />
                </video>
                <div className={styles.content}>
                  <div className={styles.title}>Paramount +</div>
                  <div className={styles.subtitle}>
                    A mountain of entertaiment
                  </div>
                </div>
                <div className={styles.overlay} />
              </Link>
            </div>
            <div className={styles.videoType2}>
              <Link href="/proyecto">
                <video autoPlay muted loop>
                  <source src="img/video-test-3.mp4" type="video/mp4" />
                </video>
                <div className={styles.content}>
                  <div className={styles.title}>Paramount +</div>
                  <div className={styles.subtitle}>
                    A mountain of entertaiment
                  </div>
                </div>
                <div className={styles.overlay} />
              </Link>
            </div>
            <div className={styles.videoType3}>
              <Link href="/proyecto">
                <video autoPlay muted loop>
                  <source src="img/video-test-4.mp4" type="video/mp4" />
                </video>
                <div className={styles.content}>
                  <div className={styles.title}>Paramount +</div>
                  <div className={styles.subtitle}>
                    A mountain of entertaiment
                  </div>
                </div>
                <div className={styles.overlay} />
              </Link>
            </div>
            <div className={styles.videoType4}>
              <Link href="/proyecto">
                <video autoPlay muted loop>
                  <source src="img/video-test-1.mp4" type="video/mp4" />
                </video>
                <div className={styles.content}>
                  <div className={styles.title}>Paramount +</div>
                  <div className={styles.subtitle}>
                    A mountain of entertaiment
                  </div>
                </div>
                <div className={styles.overlay} />
              </Link>
            </div>
          </div>
          <div className={styles.right}>
            <div className={styles.videoType2}>
              <Link href="/proyecto">
                <video autoPlay muted loop>
                  <source src="img/video-test-3.mp4" type="video/mp4" />
                </video>
                <div className={styles.content}>
                  <div className={styles.title}>Paramount +</div>
                  <div className={styles.subtitle}>
                    A mountain of entertaiment
                  </div>
                </div>
                <div className={styles.overlay} />
              </Link>
            </div>
            <div className={styles.videoType4}>
              <Link href="/proyecto">
                <video autoPlay muted loop>
                  <source src="img/video-test-1.mp4" type="video/mp4" />
                </video>
                <div className={styles.content}>
                  <div className={styles.title}>Paramount +</div>
                  <div className={styles.subtitle}>
                    A mountain of entertaiment
                  </div>
                </div>
                <div className={styles.overlay} />
              </Link>
            </div>
            <div className={styles.videoType1}>
              <Link href="/proyecto">
                <video autoPlay muted loop>
                  <source src="img/video-test-2.mp4" type="video/mp4" />
                </video>
                <div className={styles.content}>
                  <div className={styles.title}>Paramount +</div>
                  <div className={styles.subtitle}>
                    A mountain of entertaiment
                  </div>
                </div>
                <div className={styles.overlay} />
              </Link>
            </div>
            <div className={styles.videoType3}>
              <Link href="/proyecto">
                <video autoPlay muted loop>
                  <source src="img/video-test-4.mp4" type="video/mp4" />
                </video>
                <div className={styles.content}>
                  <div className={styles.title}>Paramount +</div>
                  <div className={styles.subtitle}>
                    A mountain of entertaiment
                  </div>
                </div>
                <div className={styles.overlay} />
              </Link>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
