import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

export default function Proyecto() {
  const [portafolioActivo, ponerPortfolioActivo] = useState(false);
  return (
    <>
      <Head>
        <title>CASAS - Proyecto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}>
        <div className={styles.left}>
          <Link href="/">
            <div
              className={styles.logo}
              onClick={() => ponerPortfolioActivo(false)}
            >
              <Image
                src="/img/logo.png"
                alt="casas"
                className={styles.logoImg}
                width={1773}
                height={1772}
                priority
              />
            </div>
          </Link>
        </div>
        <div
          className={styles.center}
          onClick={() => ponerPortfolioActivo(true)}
        >
          portafolio
        </div>
        <div className={styles.right}>
          <div className={styles.mail}>
            <a href="mailto:dannycasas1993@gmil.com">contacto</a>
          </div>
        </div>
      </nav>
      <main className={styles.main}>
        <section className={styles.proyecto}>
          <div className={styles.video}>
            <iframe
              src="https://player.vimeo.com/video/783452115?h=70e653bea6&title=0&byline=0&portrait=0"
              width="640"
              height="360"
              frameBorder="0"
              allow="autoplay; fullscreen; picture-in-picture"
              allowFullScreen
            ></iframe>
          </div>
          <div className={styles.content}>
            <h3>Adidas - ZX BOOST</h3>
            <p>
              <b>Créditos</b>
            </p>
            <p>
              lorem ipsumNulla ex ad in in voluptate quis mollit id dolor
              pariatur dolor dolor. Quis minim quis eu velit esse cillum.
              Ullamco elit culpa nostrud dolore laboris aute nostrud eiusmod
              consectetur aliqua. Officia consequat reprehenderit Lorem ullamco
              anim occaecat mollit ea Lorem.
            </p>
          </div>
        </section>
      </main>
      <footer className={styles.footer}>
        CASAS 2023® todos los derechos reservados
      </footer>
    </>
  );
}
